### ISSUE TITLE
BG96 support

### ISSUE THREAD

**Issue by joy4eg** [sixfab/core_manager#102]
It would be nice to have support for some old devices like BG96 (sixfab cellular IoT hat):
```
Bus 001 Device 007: ID 2c7c:0296 Quectel Wireless Solutions Co., Ltd. BG96 CAT-M1/NB-IoT modem
```
Currently, that modem is not supported:
```
sixfab-manager[904]: 2024-07-02 15:34:41,264 --> identify.py        WARNING  Modem don't exist in list of supported modems!
...
sixfab-manager[904]: 2024-07-02 15:35:05,594 --> default.py         INFO     APN is up-to-date.
sixfab-manager[904]: 2024-07-02 15:35:06,644 --> default.py         INFO     Modem mode for EPS updated succesfully
sixfab-manager[904]: 2024-07-02 15:35:06,644 --> default.py         INFO     Checking the mode of modem...
sixfab-manager[904]: 2024-07-02 15:35:07,184 --> default.py         INFO     Modem mode is not set. ECM mode will be activated soon.
sixfab-manager[904]: 2024-07-02 15:35:07,712 --> cm.py              ERROR    configure_modem() -> Error occured while setting mode configuration!
```
And then it goes into the boot loop, because it [does not](https://wiki.teltonika-networks.com/images/4/48/Quectel_BG96_AT_Commands_Manual_V2.3.pdf) support `usbnet` mode.
https://github.com/sixfab/core_manager/blob/45e1d9b0b4826ba6253d4937be0a071764118948/core_manager/helpers/modem_support/quectel.py#L22

**Comment by saeedjohar** [comment]
Our current software aims to ensure maximum uptime, providing continuous and reliable connectivity. The product you mentioned operates on Low Power Wide Area (LPWA) technology, designed for periodic connections to maximize battery life. This fundamental difference in operational focus poses a challenge for integrating support for such devices into our current software framework.
